#  mamba env create --name BSseq_mapping --file BSseq_mapping_environment.yaml 
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - snakemake=6.0.3
  - python=3.7.8
  - pandas=0.25.1
  - bowtie2=2.3.5
  - fastqc=0.11.8
  - trim-galore=0.6.4
  - samtools=1.9
  - bismark=0.20.0
  - cutadapt=2.5
  - ucsc-bedgraphtobigwig=357
  - deeptools=3.3.1
  - perl-gdgraph=1.54
  - r-base=3.5.1
  - r-essentials
  - bioconductor-segmentseq
  - bioconductor-methimpute
  - bioconductor-methylkit
  - bioconductor-dmrcaller
  - bioconductor-rtracklayer
  - rename
