#  mamba env create --name methylstar --file methylstar_environment.yaml 
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - python=2.7.16
  - r-base=3.5.1
  - fastqc=0.11.8
  - trimmomatic=0.39
  - bismark=0.19.1
  - bioconductor-methimpute
  - bioconductor-methylkit
  - bioconductor-dmrcaller
  - bioconductor-rtracklayer
  - samtools=1.9
  - bcftools=1.9
  - htslib=1.9
  - bowtie2=2.3.5.1
  - bedtools=2.29.0 
  - parallel=20220222
