#  mamba env create --name R-3.6.3 --file R-3.6.3_environment.yaml 
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - r-base=3.6.3
  - r-essentials
  - r-ggplot2
  - r-ggthemes
  - r-dplyr
  - r-tidyr
  - r-gridgraphics
  - r-gridextra
  - r-extrafont
  - r-rcolorbrewer
  - r-viridis
  - r-scales
  - bioconductor-alphabeta
