# mamba env create --name RNAseq_tetoolkit --file RNAseq_tetoolkit_environment.yaml 
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - tetoolkit=2.0.3
  - python=2.7.13
  - pysam=0.14.1
  - R=3.4.1
  - bioconductor-deseq2=1.20.0
  - STAR=2.7.0d
  - samtools=1.9
