#  mamba env create --name RNAseq_mapping --file RNAseq_mapping_environment.yaml 
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - snakemake=6.0.3
  - pandas=0.24.2
  - fastqc=0.11.8
  - bbmap=38.22
  - trimmomatic=0.38
  - cutadapt=1.18
  - pigz=2.3.4
  - hisat2=2.1.0
  - star=2.7.0d
  - samtools=1.9
  - deeptools=3.1.3
  - bedtools=2.30.0
  - bedops=2.4.39
  - minimap2=2.24
  - suppa=2.3
  - r-base=4.0.0
  - r-essentials
  - r-plyr
  - r-data.table
