#  mamba env create --name syri --file syri_environment.yaml 
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.8.10
  - mummer
  - snakemake
  - cython
  - numpy
  - scipy
  - pandas
  - biopython
  - psutil
  - matplotlib
  - python-igraph
  - pysam
